import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { blueprint } = await req.json();

    if (!blueprint) {
      return NextResponse.json(
        { error: "Blueprint missing" },
        { status: 400 }
      );
    }

    // Extract blueprint details
    const { frontend, backend } = blueprint;

    // Virtual file system to return to the frontend
    const files: Record<string, string> = {};

    // --- Generate Pages ---
    frontend.pages.forEach((page: any) => {
      files[page.file] = `export default function Page() {
  return (
    <main className="p-10 text-white">
      <h1 className="text-3xl font-bold">${page.path.replace("/", "") || "Home"} Page</h1>
      <p className="mt-2 text-gray-300">This page was generated by NextForge Pro+.</p>
    </main>
  );
}`;
    });

    // --- Generate Components ---
    frontend.components.forEach((comp: any) => {
      files[comp.file] = `export default function ${comp.name}() {
  return (
    <div className="p-4 bg-neutral-900 rounded-xl text-white">
      <p>${comp.name} component generated by NextForge Pro+.</p>
    </div>
  );
}`;
    });

    // --- Generate AI Route (if needed) ---
    if (backend.api_routes.includes("/api/generate")) {
      files["src/app/api/generate/route.ts"] = `
import { NextRequest, NextResponse } from "next/server";
import { openai } from "@/src/lib/openai";

export async function POST(req: NextRequest) {
  try {
    const { prompt } = await req.json();
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7
    });

    return NextResponse.json({
      output: completion.choices[0].message.content
    });

  } catch (err) {
    console.error("AI GENERATION ERROR:", err);
    return NextResponse.json({ error: "AI error" }, { status: 500 });
  }
}
`;
    }

    // --- Generate CRUD Route (if needed) ---
    if (backend.api_routes.includes("/api/data")) {
      files["src/app/api/data/route.ts"] = `
import { NextRequest, NextResponse } from "next/server";

let dataStore: any[] = [];

export async function GET() {
  return NextResponse.json(dataStore);
}

export async function POST(req: NextRequest) {
  const newItem = await req.json();
  dataStore.push(newItem);
  return NextResponse.json({ status: "added", item: newItem });
}
`;
    }

    // Return the full virtual filesystem
    return NextResponse.json({
      status: "ok",
      file_count: Object.keys(files).length,
      files
    });

  } catch (err) {
    console.error("SCAFFOLD ERROR:", err);
    return NextResponse.json(
      { error: "Scaffolding failed" },
      { status: 500 }
    );
  }
}
